name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.3
  - pytest
  - scipy>=1.8.0
  - pip=23.3.1
  - numpy=1.24
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
