name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pyarrow=4.0.0 
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - cython<=0.29.28
  - numpy<=1.19.5
  - pip:
      - mlflow==2.10.0
      - wandb==0.17.0


