name: components
channels:
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
  - mlflow=2.8.1
  - python=3.10
  - numpy = 1.24
=======
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - numpy = 1.24
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
>>>>>>> 57a4b3afcce7caa68c2a4421e4eb0fd0c923ecb9
